steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia.gcr.io/devops-404710/frontend/myimage:${SHORT_SHA}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia.gcr.io/devops-404710/frontend/myimage:${SHORT_SHA}']
# Docker Push
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args: 
      - "-c"
      - |
      - echo ${COMMIT_SHA} "HIII" ${SHORT_SHA} "HIi"
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
         docker_image=`cat version.txt`
         echo $docker_image
         sed -e "s#CONTAINER_IMAGE#asia.gcr.io/devops-404710/frontend/myimage:${SHORT_SHA}#" < myapp.yaml > myapp-clone.yaml
         cat myapp-clone.yaml
         export GOOGLE_APPLICATION_CREDENTIALS=./serviceaccount.json
         gcloud container clusters get-credentials gke-cluster-1 --zone us-central1 --project devops-404710
         kubectl apply -f myapp-clone.yaml 
