apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      containers:
      - name: myapp-deployment
        image: gcr.io/devops-project-368608/development/fe@sha256:46bfb3051579bd97b8f3a5d8e75b28d4a4771c91183db04b3efd373defba1049
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  ports:
  - nodePort: 30023
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: myapp-deployment
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "myfe.sathya.shop"
    http: 
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: myapp-service
            port:
              number: 3000
